tap 'AdoptOpenJDK/openjdk'
cask 'AdoptOpenJDK8'
brew 'zsh'
brew 'diff-so-fancy'
brew 'hub'
brew 'jenv'
brew 'maven'
brew 'yarn', args: ['ignore-dependencies']
brew 'zsh-autosuggestions'
brew 'zsh-completions'
tap git-chglog/git-chglog
brew git-chglog